### ISSUE TITLE
Basic Functional JSX Composition

### ISSUE THREAD

**Issue by cyberixae** [jamesplease/react-composer#64] opened 2019-03-23 12:14 UTC
I'm looking for a library to do simple functional composition of JSX elements. React-composer library looks like it might do what I need but I wonder if it has the simple use cases covered. This is not directly obvious to me from the documentation.

My current code has things that look like this.
```
<Foo x="123">
  <Bar y="456">
    <Quux />
  </Bar>
</Foo>
```

I'm wondering if the following react-composer notation would be equal to the above.
```
<Composer components={[
  <Foo x="123" />,
  <Bar y="456" />,
  <Quux />,
]} />
```

**Comment by jamesplease** [comment] 2019-03-23 14:26
React Composer was designed to work specifically with render prop components, which your example doesn’t have, so I’m skeptical that your code would work. With that said, it’s been awhile since this lib was written so there’s a chance that it would.

However, since that’s not a documented use case (and is unlikely to become one), I wouldn’t rely on it even if it did.

It might be best to fork the React Composer code to create the solution that you’re looking for.

**Comment by cyberixae** [comment] 2019-03-23 17:43
Maybe I could do something like
```
import React from 'react';
const Compose: React.FC<{}> = (props) => {
  return props.children.reduce((a, b) => React.cloneElement(a, [], [b]));
}
```
I'm just trying to find a good home for it. :-)
Or an existing (popular) way to do it.

**Comment by jamesplease** [comment] 2019-03-28 01:14
If you find something out that works well for you, feel free to leave an update into this issue! I could see it being useful for future visitors, possibly.

For now, I'm going to close this since it seems out of the scope for this specific lib.

**Closed by jamesplease** 2019-03-28 01:14 UTC
